/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "IEC61850"
 * 	found in "sv.asn"
 */

#ifndef	_SampledValues_H_
#define	_SampledValues_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SavPdu.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SampledValues_PR {
	SampledValues_PR_NOTHING,	/* No components present */
	SampledValues_PR_savPdu,
	/* Extensions may appear below */
	
} SampledValues_PR;

/* SampledValues */
typedef struct SampledValues {
	SampledValues_PR present;
	union SampledValues_u {
		SavPdu_t	 savPdu;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SampledValues_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SampledValues;

#ifdef __cplusplus
}
#endif

#endif	/* _SampledValues_H_ */
#include <asn_internal.h>
