/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "IEC61850"
 * 	found in "sv.asn"
 */

#ifndef	_SavPdu_H_
#define	_SavPdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASDU;

/* SavPdu */
typedef struct SavPdu {
	long	 noASDU;
	struct seqASDU {
		A_SEQUENCE_OF(struct ASDU) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} seqASDU;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SavPdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SavPdu;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ASDU.h"

#endif	/* _SavPdu_H_ */
#include <asn_internal.h>
