/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "IEC61850"
 * 	found in "sv.asn"
 */

#ifndef	_ASDU_H_
#define	_ASDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>
#include <NativeInteger.h>
#include "UtcTime.h"
#include "Data.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum smpSynch {
	smpSynch_none	= 0,
	smpSynch_local	= 1,
	smpSynch_global	= 2
} e_smpSynch;
typedef enum smpMod {
	smpMod_samplesPerNormalPeriod	= 0,
	smpMod_samplesPerSecond	= 1,
	smpMod_secondsPerSample	= 2
} e_smpMod;

/* ASDU */
typedef struct ASDU {
	VisibleString_t	 svID;
	VisibleString_t	*datSet	/* OPTIONAL */;
	long	 smpCnt;
	unsigned long	 confRef;
	UtcTime_t	*refrTm	/* OPTIONAL */;
	long	*smpSynch	/* OPTIONAL */;
	long	*smpRate	/* OPTIONAL */;
	Data_t	 seqData;
	long	*smpMod	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASDU_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_confRef_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASDU;

#ifdef __cplusplus
}
#endif

#endif	/* _ASDU_H_ */
#include <asn_internal.h>
