/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "IEC61850"
 * 	found in "iec61850_goose.asn"
 */

#include "IEC61850SpecificProtocol.h"

static asn_TYPE_member_t asn_MBR_IEC61850SpecificProtocol_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IEC61850SpecificProtocol, choice.goosePdu),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IECGoosePdu,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"goosePdu"
		},
};
static asn_TYPE_tag2member_t asn_MAP_IEC61850SpecificProtocol_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 0, 0, 0 } /* goosePdu */
};
static asn_CHOICE_specifics_t asn_SPC_IEC61850SpecificProtocol_specs_1 = {
	sizeof(struct IEC61850SpecificProtocol),
	offsetof(struct IEC61850SpecificProtocol, _asn_ctx),
	offsetof(struct IEC61850SpecificProtocol, present),
	sizeof(((struct IEC61850SpecificProtocol *)0)->present),
	asn_MAP_IEC61850SpecificProtocol_tag2el_1,
	1,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_IEC61850SpecificProtocol = {
	"IEC61850SpecificProtocol",
	"IEC61850SpecificProtocol",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_IEC61850SpecificProtocol_1,
	1,	/* Elements count */
	&asn_SPC_IEC61850SpecificProtocol_specs_1	/* Additional specs */
};

