/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "IEC61850"
 * 	found in "iec61850_goose.asn"
 */

#ifndef	_IEC61850SpecificProtocol_H_
#define	_IEC61850SpecificProtocol_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IECGoosePdu.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IEC61850SpecificProtocol_PR {
	IEC61850SpecificProtocol_PR_NOTHING,	/* No components present */
	IEC61850SpecificProtocol_PR_goosePdu
} IEC61850SpecificProtocol_PR;

/* IEC61850SpecificProtocol */
typedef struct IEC61850SpecificProtocol {
	IEC61850SpecificProtocol_PR present;
	union IEC61850SpecificProtocol_u {
		IECGoosePdu_t	 goosePdu;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IEC61850SpecificProtocol_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IEC61850SpecificProtocol;

#ifdef __cplusplus
}
#endif

#endif	/* _IEC61850SpecificProtocol_H_ */
#include <asn_internal.h>
