#!/bin/bash

echo "\nstart building...\n"

echo "\nclear all...\n"
make clean

echo "convert file...\n"
mv dbsync_task.cpp dbsync_task.cpp_bak
iconv -f utf-8 -t gbk dbsync_task.cpp_bak -o dbsync_task.cpp

echo "\nmake...\n"
if [ -f "$1" ]; then
make -f $1 clean
make -f $1
else
make
fi

echo "convert file back...\n"
rm -f dbsync_task.cpp
mv dbsync_task.cpp_bak dbsync_task.cpp

echo "\nfinish build\n"
 
