/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "IEC61850"
 * 	found in "iec61850_goose.asn"
 */

#include "IECGoosePdu.h"

static asn_TYPE_member_t asn_MBR_allData_13[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_Data,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_allData_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_allData_specs_13 = {
	sizeof(struct allData),
	offsetof(struct allData, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_allData_13 = {
	"allData",
	"allData",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_allData_tags_13,
	sizeof(asn_DEF_allData_tags_13)
		/sizeof(asn_DEF_allData_tags_13[0]) - 1, /* 1 */
	asn_DEF_allData_tags_13,	/* Same as above */
	sizeof(asn_DEF_allData_tags_13)
		/sizeof(asn_DEF_allData_tags_13[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_allData_13,
	1,	/* Single element */
	&asn_SPC_allData_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_IECGoosePdu_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IECGoosePdu, gocbRef),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"gocbRef"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IECGoosePdu, timeAllowedtoLive),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"timeAllowedtoLive"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IECGoosePdu, datSet),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"datSet"
		},
	{ ATF_POINTER, 1, offsetof(struct IECGoosePdu, goID),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"goID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IECGoosePdu, t),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UtcTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"t"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IECGoosePdu, stNum),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"stNum"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IECGoosePdu, sqNum),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sqNum"
		},
	{ ATF_POINTER, 1, offsetof(struct IECGoosePdu, simulation),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"simulation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IECGoosePdu, confRev),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"confRev"
		},
	{ ATF_POINTER, 1, offsetof(struct IECGoosePdu, ndsCom),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ndsCom"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IECGoosePdu, numDatSetEntries),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numDatSetEntries"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IECGoosePdu, allData),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		0,
		&asn_DEF_allData_13,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"allData"
		},
};
static ber_tlv_tag_t asn_DEF_IECGoosePdu_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_IECGoosePdu_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* gocbRef */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* timeAllowedtoLive */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* datSet */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* goID */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* t */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* stNum */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* sqNum */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* simulation */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* confRev */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* ndsCom */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* numDatSetEntries */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 } /* allData */
};
static asn_SEQUENCE_specifics_t asn_SPC_IECGoosePdu_specs_1 = {
	sizeof(struct IECGoosePdu),
	offsetof(struct IECGoosePdu, _asn_ctx),
	asn_MAP_IECGoosePdu_tag2el_1,
	12,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_IECGoosePdu = {
	"IECGoosePdu",
	"IECGoosePdu",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_IECGoosePdu_tags_1,
	sizeof(asn_DEF_IECGoosePdu_tags_1)
		/sizeof(asn_DEF_IECGoosePdu_tags_1[0]), /* 1 */
	asn_DEF_IECGoosePdu_tags_1,	/* Same as above */
	sizeof(asn_DEF_IECGoosePdu_tags_1)
		/sizeof(asn_DEF_IECGoosePdu_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_IECGoosePdu_1,
	12,	/* Elements count */
	&asn_SPC_IECGoosePdu_specs_1	/* Additional specs */
};

